# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Experimental iOS (arm64) configuration.
# Usage on a Mac:
#   cmake -S blender-5.2.0 -B build_ios \
#         -C build_files/cmake/config/blender_ios.cmake \
#         -DCMAKE_TOOLCHAIN_FILE=../ios/cmake/ios.toolchain.cmake

include(${CMAKE_CURRENT_LIST_DIR}/blender_lite.cmake)

set(IOS ON CACHE BOOL "" FORCE)
set(WITH_PYTHON_MODULE OFF CACHE BOOL "" FORCE)

set(WITH_GHOST_SDL            ON  CACHE BOOL "" FORCE)
set(WITH_BLENDER_THUMBNAILER  OFF CACHE BOOL "" FORCE)
set(WITH_GHOST_X11            OFF CACHE BOOL "" FORCE)
set(WITH_GHOST_WAYLAND        OFF CACHE BOOL "" FORCE)
set(WITH_GHOST_XDND           OFF CACHE BOOL "" FORCE)
set(WITH_X11_XINPUT           OFF CACHE BOOL "" FORCE)
set(WITH_VULKAN_BACKEND       ON  CACHE BOOL "" FORCE)
set(WITH_OPENGL_BACKEND       OFF CACHE BOOL "" FORCE)
set(WITH_METAL_BACKEND        OFF CACHE BOOL "" FORCE)
set(WITH_HEADLESS             OFF CACHE BOOL "" FORCE)
set(WITH_PYTHON               ON  CACHE BOOL "" FORCE)
set(WITH_PYTHON_INSTALL       OFF CACHE BOOL "" FORCE)
set(WITH_INPUT_NDOF           OFF CACHE BOOL "" FORCE)
set(WITH_INPUT_IME            OFF CACHE BOOL "" FORCE)
set(WITH_CPU_CHECK            OFF CACHE BOOL "" FORCE)
set(WITH_INSTALL_PORTABLE     ON  CACHE BOOL "" FORCE)
set(WITH_COMPILER_SIMD        OFF CACHE BOOL "" FORCE)
set(WITH_TBB                  ON  CACHE BOOL "" FORCE)
set(WITH_TBB_MALLOC_PROXY     OFF CACHE BOOL "" FORCE)
set(WITH_XR_OPENXR            OFF CACHE BOOL "" FORCE)
set(WITH_PULSEAUDIO           OFF CACHE BOOL "" FORCE)
set(WITH_PIPEWIRE             OFF CACHE BOOL "" FORCE)
set(WITH_JACK                 OFF CACHE BOOL "" FORCE)
set(WITH_OPENAL               OFF CACHE BOOL "" FORCE)
set(WITH_SDL_AUDIO            OFF CACHE BOOL "" FORCE)
set(WITH_AUDASPACE            OFF CACHE BOOL "" FORCE)
set(WITH_LIBS_PRECOMPILED     ON  CACHE BOOL "" FORCE)
set(WITH_STATIC_LIBS          ON  CACHE BOOL "" FORCE)
set(WITH_SYSTEM_FREETYPE      OFF CACHE BOOL "" FORCE)
set(WITH_GHOST_DEBUG          OFF CACHE BOOL "" FORCE)
set(WITH_UNITY_BUILD          ON  CACHE BOOL "" FORCE)
set(WITH_GTESTS               OFF CACHE BOOL "" FORCE)
set(WITH_DOC_MANPAGE          OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES               ON  CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_CUDA   OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_HIP    OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_OPTIX  OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_ONEAPI OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_DEVICE_METAL  OFF CACHE BOOL "" FORCE)
set(WITH_HARFBUZZ             OFF CACHE BOOL "" FORCE)
set(WITH_FRIBIDI              OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_OSL           OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_EMBREE        OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_PATH_GUIDING  OFF CACHE BOOL "" FORCE)
set(WITH_ASSERT_RELEASE       OFF CACHE BOOL "" FORCE)
